### PR TITLE
style navbar components

### PR DESCRIPTION
**Pull request by yaredtekle022**
**These lis of activities were done **

> Styled navbar components

### CODE REVIEW

**Review by RileyManda — CHANGES_REQUESTED** [review]
## Hi @yaredtekle022   , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

giphy


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
✔ Clean and organized code✔
✔ Very detailed and descriptive pull request summary👋 
✔ Readme looks well polished and professional 
✔ No linter Errors

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by RileyManda — COMMENTED** [review]
Hi @yaredtekle022 
You did great aligning the menu items to the top right of the navbar-/header:
I would suggest that you push the menu items to the top far right to match the design.

Requirements:
space-travelers__rockets

Your design:

Screen Shot 2023-08-02 at 8 54 59 AM

**Comment by yaredtekle022** [comment]
Thanks for your review

**Review by RileyManda — APPROVED** [review]
# Approved 🥳

Hi @yaredtekle022  🙋‍♀️

Great job implementing the changes suggested by the previous reviewer 💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**



## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Styling is looking great, perfect!
-  ✅ Great work using the right GitHub Flow 
-  ✅ Good branch name. Great job!
-  ✅ Linters are working properly, great job! 
-  ✅ Menu items are aligned properly 

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_**Please see the comments under review**_

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
